### PR TITLE
Edits to timeseries docs

### PR DESCRIPTION
**Pull request by wafels**
Alex,
I made some minor changes to the docs in your timeseries branch, mainly for line length and clarity.  I have a couple of questions as well.  What remedial action should people take when manipulating time series data with astropy units to make sure all is well, and what is the problem with astropy table mixins?  I think the term mixin is quite technical and may be confusing to some users.

Thanks!

### CODE REVIEW

**Comment by Alex-Ian-Hamilton** [comment]
Cool
When you say remedial actions, do you mean how to maintain unit consistency?
In that case you would have to modify the TimeSeries.units dictionary manually, using the heading of the column as the key for accessing the relevant entry.
We had thought to try and keep unit consistency automatically based on the operations used, but that would be impractical as a user can essentially modify the data manually and if the class tried to maintain unit consistency automatically in some cases/operations but can't in others then that would make it all more confusing while simultaneously making a huge amount more work.

By problem, do you mean when I mention "limits the versatility"?
The mixin column is stored as a single immutable object in the table, this means you can't perform row operations on the table, like adding/removing columns or sorting it.

**Comment by wafels** [comment]
Thanks for the explanations.  I think it best to be explicit and write that
the user must check the units, and update accordingly.  I'll make some edits

Also, if I create a TimeSeries from an astropy Table, does that mean that
the time index consists of astropy Time objects and not pandas datetime
objects?  Did I get that right?  I tried the very first example in the docs
and got


*In [16]: my_timeseries.data.index[0]Out[16]: Timestamp('2012-05-31
23:59:59.088999')*

and the astropy Table to TimeSeries conversion


*In [17]: ts_table.data.index[0]Out[17]: <Time object: scale='utc'
format='datetime' value=2017-01-22 20:50:07.541127>*

Is this the expected behavior?








On Mon, Jan 23, 2017 at 5:38 PM, Alex-Ian-Hamilton <notifications@github.com

**Comment by Alex-Ian-Hamilton** [comment]
That is an interesting question, I hadn't noticed that and I think that may be in error.
From the looks of it I can't seem to truncate the ts_table TimeSeries, which implies I should look at converting to a pandas.tseries.index.DatetimeIndex object if possible.

In playing around I also notice that I can't change a TS to Table and back:
ts.TimeSeries(my_timeseries.to_table())
Which I guess is because I don't declare a table.Primary_Key property for the output table.
So that's a couple of tweaks I guess I should make.

@Cadair, is that right?

**Comment by Cadair** [comment]
Yes, I think we need to cast to Pandas Time on construction of the DataFrame

**Pull request merged**
